#!/usr/bin/env python3
"""Render the ESP-Mosaico 5x8 wordmark and emit RGB565 RLE for boot splash."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


# One 5x8 cell is 100 font units; UPM is 1000, so 1px/cell uses size 10.
CELL_UNITS = 100
UNITS_PER_EM = 1000
DEFAULT_TEXT = "mosaico"
DEFAULT_COLOR = "#FF4C01"
DEFAULT_CELL_PX = 8
DEFAULT_PAD_CELLS = 1
DEFAULT_DOT_RATIO = 0.58
SUPERSAMPLE = 4


def lanczos_filter() -> int:
    """Return the Pillow resampling constant on both old and new releases."""
    resampling = getattr(Image, "Resampling", None)
    return resampling.LANCZOS if resampling is not None else Image.LANCZOS


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)


def rle_encode(pixels: list[int]) -> list[tuple[int, int]]:
    runs: list[tuple[int, int]] = []
    color = pixels[0]
    count = 0
    for pixel in pixels:
        if pixel == color and count < 0xFFFF:
            count += 1
            continue
        runs.append((count, color))
        color = pixel
        count = 1
    runs.append((count, color))
    return runs


def raster_cells(font_path: Path, text: str) -> Image.Image:
    font = ImageFont.truetype(str(font_path), size=UNITS_PER_EM // CELL_UNITS)
    dummy = Image.new("L", (1, 1), 0)
    left, top, right, bottom = ImageDraw.Draw(dummy).textbbox(
        (0, 0), text, font=font)
    bitmap = Image.new("L", (right - left, bottom - top), 0)
    ImageDraw.Draw(bitmap).text((-left, -top), text, font=font, fill=255)
    return bitmap.point(lambda value: 255 if value > 128 else 0)


def render_wordmark(
    font_path: Path,
    text: str,
    color: str,
    cell_px: int,
    pad_cells: int,
    dot_ratio: float,
) -> Image.Image:
    cells = raster_cells(font_path, text)
    pad = pad_cells * cell_px
    width = cells.width * cell_px + pad * 2
    height = cells.height * cell_px + pad * 2
    ss = SUPERSAMPLE
    hi = Image.new("RGB", (width * ss, height * ss), (0, 0, 0))
    draw = ImageDraw.Draw(hi)
    radius = (cell_px * dot_ratio * ss) / 2.0
    for y in range(cells.height):
        for x in range(cells.width):
            if cells.getpixel((x, y)) == 0:
                continue
            cx = (pad + x * cell_px + cell_px / 2.0) * ss
            cy = (pad + y * cell_px + cell_px / 2.0) * ss
            draw.ellipse(
                (cx - radius, cy - radius, cx + radius, cy + radius),
                fill=color,
            )
    antialiased = hi.resize((width, height), lanczos_filter())
    orange = Image.new("RGB", antialiased.size, color)
    # Keep the generated firmware asset strictly two-color. Supersampling is
    # used only to choose smooth, round dot boundaries.
    mask = antialiased.convert("L").point(
        lambda value: 255 if value >= 24 else 0)
    return Image.composite(orange, Image.new("RGB", antialiased.size), mask)


def write_header(path: Path, image: Image.Image) -> None:
    pixels = [rgb565(red, green, blue) for red, green, blue in image.getdata()]
    runs = rle_encode(pixels)
    foreground = next(color for color in pixels if color != 0)
    bitmap = []
    for offset in range(0, len(pixels), 8):
        byte = 0
        for bit, pixel in enumerate(pixels[offset:offset + 8]):
            if pixel != 0:
                byte |= 0x80 >> bit
        bitmap.append(byte)
    lines = [
        "/* Generated by components/mosaico_boot_splash/tools/generate_boot_logo.py. */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define MOSAIC_BOOT_LOGO_WIDTH {image.width}U",
        f"#define MOSAIC_BOOT_LOGO_HEIGHT {image.height}U",
        "",
        "typedef struct {",
        "    uint16_t count;",
        "    uint16_t color;",
        "} mosaic_boot_logo_run_t;",
        "",
        "static const mosaic_boot_logo_run_t s_mosaic_boot_logo_runs[] = {",
    ]
    lines.extend(f"    {{{count}U, 0x{color:04X}U}}," for count, color in runs)
    lines.extend([
        "};",
        "",
        "#define MOSAIC_BOOT_LOGO_RUN_COUNT \\",
        "    (sizeof(s_mosaic_boot_logo_runs) / sizeof(s_mosaic_boot_logo_runs[0]))",
        "",
        f"#define MOSAIC_BOOT_LOGO_COLOR 0x{foreground:04X}U",
        "static const uint8_t s_mosaic_boot_logo_bitmap[] = {",
    ])
    for offset in range(0, len(bitmap), 16):
        values = ", ".join(f"0x{value:02X}U" for value in bitmap[offset:offset + 16])
        lines.append(f"    {values},")
    lines.extend(["};", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--text", default=DEFAULT_TEXT)
    parser.add_argument("--color", default=DEFAULT_COLOR)
    parser.add_argument("--cell-px", type=int, default=DEFAULT_CELL_PX)
    parser.add_argument("--pad-cells", type=int, default=DEFAULT_PAD_CELLS)
    parser.add_argument("--dot-ratio", type=float, default=DEFAULT_DOT_RATIO)
    parser.add_argument("--png", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    image = render_wordmark(
        args.font, args.text, args.color, args.cell_px, args.pad_cells,
        args.dot_ratio)
    args.png.parent.mkdir(parents=True, exist_ok=True)
    image.save(args.png)
    write_header(args.output, image)
    print(f"wrote {args.png} ({image.width}x{image.height}) and {args.output}")


if __name__ == "__main__":
    main()
