#!/usr/bin/env python3
"""Encode the original web forecast glyphs for dynamic List rows."""

from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "weather_forecast_icon_data.h"
NAMES = ("sunny", "cloudy", "snow", "windy", "thunder")


def qoi_rgb(image):
    pixels = list(image.convert("RGB").getdata())
    data = bytearray(b"qoif")
    data.extend(image.width.to_bytes(4, "big"))
    data.extend(image.height.to_bytes(4, "big"))
    data.extend((3, 0))
    table = [(0, 0, 0, 0)] * 64
    previous = (0, 0, 0, 255)
    run = 0
    for index, (red, green, blue) in enumerate(pixels):
        pixel = (red, green, blue, 255)
        if pixel == previous:
            run += 1
            if run == 62 or index == len(pixels) - 1:
                data.append(0xC0 | (run - 1))
                run = 0
            continue
        if run:
            data.append(0xC0 | (run - 1))
            run = 0
        slot = (red * 3 + green * 5 + blue * 7 + 255 * 11) % 64
        if table[slot] == pixel:
            data.append(slot)
        else:
            table[slot] = pixel
            pr, pg, pb, _ = previous
            dr, dg, db = red - pr, green - pg, blue - pb
            if -2 <= dr <= 1 and -2 <= dg <= 1 and -2 <= db <= 1:
                data.append(0x40 | ((dr + 2) << 4) | ((dg + 2) << 2) | db + 2)
            else:
                dr_dg, db_dg = dr - dg, db - dg
                if -32 <= dg <= 31 and -8 <= dr_dg <= 7 and -8 <= db_dg <= 7:
                    data.extend((0x80 | (dg + 32), (dr_dg + 8) << 4 | db_dg + 8))
                else:
                    data.extend((0xFE, red, green, blue))
        previous = pixel
    data.extend(b"\0\0\0\0\0\0\0\1")
    return data


def main():
    lines = ["/* Generated by scene/generate_forecast_icon_data.py. */",
             "#pragma once", "", "#include <stdint.h>", ""]
    for name in NAMES:
        source = Image.open(HERE.parent / "assets" / f"forecast_{name}.png").convert("RGBA")
        canvas = Image.new("RGBA", (24, 24), (24, 24, 25, 255))
        canvas.alpha_composite(source)
        encoded = qoi_rgb(canvas)
        lines.append(f"static const uint8_t weather_forecast_icon_{name}[] = {{")
        for start in range(0, len(encoded), 12):
            lines.append("    " + ", ".join(f"0x{x:02x}" for x in encoded[start:start + 12]) + ",")
        lines.extend(("};", ""))
    OUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
