set(MOSAIC_APP_NAME interact)
set(MOSAIC_APP_MODULE_SOURCE interact_app.c)
set(MOSAIC_APP_MODULE_SYMBOL mosaic_interact_app)
set(MOSAIC_APP_BUNDLE generated/interact.gspb)
set(MOSAIC_APP_SCENE_DIR scene)
set(MOSAIC_APP_SCENE_JSON scene/interact_480.json)
set(MOSAIC_APP_GENERATOR scene/gen_scene.py)
set(MOSAIC_APP_EXTRA_SOURCES interact_backend.c)
set(MOSAIC_APP_SCENE_SOURCES assets/interact_board.png scene/rotate_scene.py)
set(MOSAIC_APP_GENERATED_HEADERS interact_binds.h interact_actions.h interact_objects.h interact_rotated_text.h)
