#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
# SPDX-License-Identifier: Apache-2.0
"""Generate the encoded Settings root-row icons used by the List binder."""

from pathlib import Path

from PIL import Image, ImageDraw


HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "settings_root_icon_data.h"
LANCZOS = getattr(Image, "Resampling", Image).LANCZOS
ICONS = {
    "ai": HERE / "settings_root_ai.png",
    "channels": HERE / "settings_root_channels.png",
    "network": HERE / "settings_root_network.png",
    "display": HERE / "settings_root_display.png",
    "sound": HERE / "settings_root_sound.png",
    "security": HERE / "settings_root_security.png",
    "battery": None,
    "about": HERE / "settings_root_about.png",
}

# Pillow < 9.1 exposes resampling filters directly on Image, while newer
# releases group them under Image.Resampling.
LANCZOS = getattr(Image, "Resampling", Image).LANCZOS


def draw_battery_icon() -> Image.Image:
    """Draw a crisp full-battery glyph matching the Settings icon set."""
    scale = 4
    color = (214, 214, 222, 255)
    icon = Image.new("RGBA", (48 * scale, 48 * scale), (0, 0, 0, 0))
    draw = ImageDraw.Draw(icon)

    def box(coords: tuple[int, int, int, int]) -> tuple[int, int, int, int]:
        return tuple(value * scale for value in coords)

    draw.rounded_rectangle(
        box((37, 20, 43, 28)), radius=2 * scale, fill=color)
    draw.rounded_rectangle(
        box((6, 14, 38, 34)), radius=5 * scale,
        outline=color, width=3 * scale)
    for left, right in ((10, 14), (16, 20), (22, 26), (28, 33)):
        draw.rounded_rectangle(
            box((left, 18, right, 30)), radius=1 * scale, fill=color)

    return icon.resize((48, 48), LANCZOS)


def qoi_encode_rgb(image: Image.Image) -> bytes:
    """Encode an RGB image as a small QOI stream without external tools."""
    rgb = image.convert("RGB")
    width, height = rgb.size
    output = bytearray(b"qoif")
    output.extend(width.to_bytes(4, "big"))
    output.extend(height.to_bytes(4, "big"))
    output.extend((3, 0))
    index = [(0, 0, 0, 0)] * 64
    previous = (0, 0, 0, 255)
    run = 0
    pixels = list(rgb.getdata())
    for pixel_index, (red, green, blue) in enumerate(pixels):
        pixel = (red, green, blue, 255)
        if pixel == previous:
            run += 1
            if run == 62 or pixel_index == len(pixels) - 1:
                output.append(0xC0 | (run - 1))
                run = 0
            continue
        if run:
            output.append(0xC0 | (run - 1))
            run = 0
        slot = (red * 3 + green * 5 + blue * 7 + 255 * 11) % 64
        if index[slot] == pixel:
            output.append(slot)
        else:
            index[slot] = pixel
            pr, pg, pb, _ = previous
            dr, dg, db = red - pr, green - pg, blue - pb
            if -2 <= dr <= 1 and -2 <= dg <= 1 and -2 <= db <= 1:
                output.append(0x40 | ((dr + 2) << 4) |
                              ((dg + 2) << 2) | (db + 2))
            else:
                dr_dg, db_dg = dr - dg, db - dg
                if -32 <= dg <= 31 and -8 <= dr_dg <= 7 and \
                        -8 <= db_dg <= 7:
                    output.extend((0x80 | (dg + 32),
                                   ((dr_dg + 8) << 4) | (db_dg + 8)))
                else:
                    output.extend((0xFE, red, green, blue))
        previous = pixel
    output.extend(b"\0\0\0\0\0\0\0\1")
    return bytes(output)


def main() -> None:
    lines = [
        "/* Generated by scene/generate_root_icon_data.py. */",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]
    for name, path in ICONS.items():
        source = (draw_battery_icon() if name == "battery"
                  else Image.open(path).convert("RGBA"))
        icon = Image.new("RGBA", (48, 48), (0, 0, 0, 0))
        icon.alpha_composite(source, ((48 - source.width) // 2,
                                      (48 - source.height) // 2))
        background = Image.new("RGB", icon.size, (0, 0, 0))
        background.paste(icon, mask=icon.getchannel("A"))
        data = qoi_encode_rgb(background)
        lines.append(f"static const uint8_t settings_root_icon_{name}[] = {{")
        for offset in range(0, len(data), 12):
            chunk = data[offset:offset + 12]
            lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
        lines.extend(("};", ""))
    OUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
