#!/usr/bin/env python3
"""Generate Launchpad-owned A8 title bitmaps."""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
FONT = HERE.parent / "apps" / "settings" / "scene" / "settings_font.ttf"
OUT_H = HERE / "mosaic_app_shell_titles.h"
OUT_C = HERE / "mosaic_app_shell_titles.c"
ASSETS = (
    *((title, 30) for title in
      ("Camera", "我的作品", "SETTINGS", "IMU", "Env", "TOF", "Works",
       "Breakout")),
    ("Battery Low", 20),
    ("Please charge your device", 18),
    ("Battery Critically Low", 20),
    ("Shutting down", 18),
)


def symbol(index: int) -> str:
    return f"s_title_{index}"


assets = []
for title, font_size in ASSETS:
    font = ImageFont.truetype(str(FONT), font_size)
    left, top, right, bottom = font.getbbox(title)
    width = max(1, right - left)
    height = max(1, bottom - top)
    image = Image.new("L", (width, height), 0)
    ImageDraw.Draw(image).text((-left, -top), title, font=font, fill=255)
    assets.append((title, width, height, bytes(image.getdata())))

OUT_H.write_text("""/* Generated by generate_app_shell_titles.py. */
#pragma once
#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char *title;
    const uint8_t *a8;
    size_t size;
    uint16_t width;
    uint16_t height;
    uint16_t stride;
} mosaic_app_shell_title_asset_t;

const mosaic_app_shell_title_asset_t *mosaic_app_shell_title_asset(
    const char *title);
""", encoding="utf-8")

lines = [
    "/* Generated by generate_app_shell_titles.py. */",
    '#include "mosaic_app_shell_titles.h"',
    "#include <string.h>",
    "",
]
for index, (_, _, _, pixels) in enumerate(assets):
    lines.append(f"static const uint8_t {symbol(index)}[] = {{")
    for offset in range(0, len(pixels), 16):
        chunk = ", ".join(str(value) for value in pixels[offset:offset + 16])
        lines.append(f"    {chunk},")
    lines.extend(("};", ""))
lines.append("static const mosaic_app_shell_title_asset_t s_titles[] = {")
for index, (title, width, height, _) in enumerate(assets):
    escaped = title.encode("unicode_escape").decode("ascii")
    if not title.isascii():
        literal = '"' + ''.join(f"\\x{b:02x}" for b in title.encode()) + '"'
    else:
        literal = f'"{escaped}"'
    lines.append(
        f"    {{{literal}, {symbol(index)}, sizeof({symbol(index)}), "
        f"{width}, {height}, {width}}},")
lines.extend((
    "};",
    "",
    "const mosaic_app_shell_title_asset_t *mosaic_app_shell_title_asset(",
    "    const char *title)",
    "{",
    "    if (title == NULL) return NULL;",
    "    for (size_t i = 0; i < sizeof(s_titles) / sizeof(s_titles[0]); ++i) {",
    "        if (strcmp(s_titles[i].title, title) == 0) return &s_titles[i];",
    "    }",
    "    return NULL;",
    "}",
    "",
))
OUT_C.write_text("\n".join(lines), encoding="utf-8")
print(f"generated {len(assets)} App Shell title assets")
