/* Generated by generate_app_shell_titles.py. */
#pragma once
#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char *title;
    const uint8_t *a8;
    size_t size;
    uint16_t width;
    uint16_t height;
    uint16_t stride;
} mosaic_app_shell_title_asset_t;

const mosaic_app_shell_title_asset_t *mosaic_app_shell_title_asset(
    const char *title);
