# SPDX-License-Identifier: Apache-2.0
"""Bake the PCB, text and hit rectangles into a counterclockwise scene."""
import json
import os
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def rotate_scene(objects, here, font_path):
    generated = Path(os.environ.get("MOSAIC_GENERATED_DIR", here.parent / "generated")).resolve()
    assets = generated / "rotated_assets"
    assets.mkdir(parents=True, exist_ok=True)
    fields = {
        "status": ["", "Connecting...", "Init failed", "Open failed", "Left connected", "Right connected", "Board in use", "Connect interaction board", "Board disconnected", "Sensor read failed", "LED write failed", "Out of memory", "Preview - no hardware"],
        "ir_status": ["", "IR sending", "IR sent", "IR failed"],
        "slot": ["AUTO >", "LEFT >", "RIGHT >"],
    }
    widths = [obj["w"] for obj in objects]
    rotated = []
    parents = {}
    bindings = {}

    def text_image(obj, text, stem):
        bitmap = Image.new("RGBA", (obj["w"], obj["h"]))
        if text:
            font = ImageFont.truetype(font_path, obj["font_size"])
            draw = ImageDraw.Draw(bitmap)
            box = draw.textbbox((0, 0), text, font=font)
            width, height = box[2] - box[0], box[3] - box[1]
            align = obj.get("text_align", "center" if obj["type"] == "button" else "left")
            x = (obj["w"] - width) // 2 if align == "center" else obj["w"] - width if align == "right" else 0
            draw.text((x - box[0], (obj["h"] - height) // 2 - box[1]), text, font=font, fill=obj["fg_color"])
        path = assets / f"{stem}.png"
        bitmap.transpose(Image.Transpose.ROTATE_90).save(path)
        return str(path)

    for index, source in enumerate(objects):
        obj = dict(source)
        parent = obj["parent"]
        if parent >= 0:
            obj.update(parent=parents[parent], x=source["y"], y=widths[parent] - source["x"] - source["w"], w=source["h"], h=source["w"])
        parents[index] = len(rotated)
        field = source.get("bind")
        if field == "light":
            # Reuse rotated digit sprites instead of storing 101 full readings.
            for digit in range(4):
                glyph = dict(source, x=source["x"] + source["w"] - 40 + digit * 10, w=10, text_align="center")
                values = [" ", "-", *"0123456789"] if digit < 3 else ["%"]
                for variant, text in enumerate(values):
                    name = f"light_{digit}_{variant}"
                    sprite = dict(type="image", parent=obj["parent"], x=glyph["y"], y=widths[parent] - glyph["x"] - glyph["w"], w=glyph["h"], h=glyph["w"], name=name,
                                  image=text_image(glyph, text, name))
                    if digit < 3:
                        sprite.update(bind=name, bind_target="visible", hidden=True)
                        bindings.setdefault(f"light_{digit}", []).append((text, name))
                    rotated.append(sprite)
            continue
        if source["type"] == "image":
            path = assets / f"image_{index}.png"
            with Image.open(here / source["image"]) as bitmap:
                bitmap.transpose(Image.Transpose.ROTATE_90).save(path)
            obj["image"] = str(path)
        if source["type"] in ("label", "button") and (source.get("text") or field in fields):
            if source["type"] == "button":
                obj.pop("bind", None)
                obj["text"] = ""
                rotated.append(obj)
            variants = fields.get(field, [source["text"]])
            for variant, text in enumerate(variants):
                name = f"{field}_{variant}" if field in fields else f"text_{index}"
                sprite = {key: obj[key] for key in ("parent", "x", "y", "w", "h")}
                sprite.update(type="image", image=text_image(source, text, name), name=name)
                if source.get("callback"):
                    sprite["callback"] = source["callback"]
                if field in fields:
                    sprite.update(bind=name, bind_target="visible", hidden=True)
                    bindings.setdefault(field, []).append((text, name))
                rotated.append(sprite)
        else:
            rotated.append(obj)

    # Dynamic strings are selected from pre-rotated sprites, not rotated at runtime.
    header = ["/* Generated by rotate_scene.py. */", "#pragma once", '#include "interact_binds.h"', '#include "esp_gsp.h"', "#include <string.h>",
              "typedef struct { const char *text; unsigned short bind; } interact_text_variant_t;"]
    for field, entries in bindings.items():
        header.append(f"static const interact_text_variant_t interact_{field}_variants[] = {{")
        header.extend(f"    {{{json.dumps(text)}, GSP_BIND_{name.upper()}}}," for text, name in entries)
        header.append("};")
        header.append(f"static inline void interact_{field}_set_text(esp_gsp_handle_t ui, const char *text, int *previous) {{")
        header.append(f"    const interact_text_variant_t *variants = interact_{field}_variants;")
        header.append(f"    int selected = 0; for (unsigned i = 0; i < {len(entries)}; ++i) if (!strcmp(variants[i].text, text)) {{ selected = i; break; }}")
        if field == "status":
            header.append('    if (!strncmp(text, "Open failed", 11)) selected = 3;')
        header.extend(["    if (selected == *previous) return;", "    if (*previous >= 0) esp_gsp_set_visible(ui, variants[*previous].bind, false);",
                       "    esp_gsp_set_visible(ui, variants[selected].bind, true);", "    *previous = selected;", "}"])
    header.extend(["static inline void interact_light_set_text(esp_gsp_handle_t ui, const char *text, int previous[3]) {",
                   '    char padded[4] = "   "; size_t count = strlen(text);',
                   "    if (count && text[count - 1] == '%') --count;",
                   "    if (count > 3) count = 3;",
                   "    memcpy(padded + 3 - count, text, count); char character[2] = {0};"])
    for digit in range(3):
        header.append(f"    character[0] = padded[{digit}]; interact_light_{digit}_set_text(ui, character, &previous[{digit}]);")
    header.append("}")
    (generated / "interact_rotated_text.h").write_text("\n".join(header) + "\n")
    return rotated
